name: null
favicon: null
layout_spectrum: 0.13652
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#eeebe2'
    - '#555650'
    - '#b9b298'
    - '#da4737'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: 5e825a94-3f74-4ec3-898f-4327078299d4
    url: null
